name: Build APK

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-all
          pip install --user buildozer cython

      - name: Build APK
        run: |
          ~/.local/bin/buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
